using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System.Text;

namespace GeneratorLibrary.Composites
{
    /// <summary>
    /// Generates one script per class marked with [Composite], into whichever assembly declares that class.
    /// </summary>
    [Generator]
    public class CompositeGenerator : IIncrementalGenerator
    {
        private const string CompositeAttributeName = "reromanlee.Mocker.CompositeAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<TypeTarget> composites = context.FindAllByAttribute(CompositeAttributeName);

            context.RegisterSourceOutput(composites, (productionContext, composite) =>
            {
                productionContext.AddLocalScript(composite, BuildScript(composite));
            });
        }

        private static string BuildScript(TypeTarget composite)
        {
            StringBuilder script = new StringBuilder();
            string indent = composite.HasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (composite.HasNamespace)
            {
                script.AppendLine($"namespace {composite.Namespace}");
                script.AppendLine("{");
            }

            script.AppendLine($"{indent}partial class {composite.Name}");
            script.AppendLine($"{indent}{{");
            script.AppendLine($"{indent}    public static void LogComposite()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        UnityEngine.Debug.Log(\"Composite {composite.Name} was generated into {composite.AssemblyName}.\");");
            script.AppendLine($"{indent}    }}");
            script.AppendLine($"{indent}}}");

            if (composite.HasNamespace)
            {
                script.AppendLine("}");
            }

            return script.ToString();
        }
    }
}
