using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the configuration a composite is constructed with: one class per branch, mirroring the API,
    /// so that choices.Ads.Interstitial sits where Ads.Interstitial does. Plain classes holding enums, so
    /// nothing here depends on the project or on Unity.
    /// </summary>
    internal static class MockerChoicesWriter
    {
        /// <summary>
        /// Writes the whole choices tree for one composite.
        /// </summary>
        /// <param name="context">Context the script is added to.</param>
        /// <param name="scope">The composite and everything under it.</param>
        public static void Write(SourceProductionContext context, MockerScope scope)
        {
            StringBuilder script = new StringBuilder();
            bool hasNamespace = scope.Composite.Type.HasNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (hasNamespace)
            {
                script.AppendLine($"namespace {scope.Composite.Type.Namespace}");
                script.AppendLine("{");
            }

            for (int index = 0; index < scope.Branches.Count; index++)
            {
                if (index > 0)
                {
                    script.AppendLine();
                }

                AppendBranch(script, indent, scope, scope.Branches[index]);
            }

            if (hasNamespace)
            {
                script.AppendLine("}");
            }

            context.AddScript(scope.Composite.Type.FullName + ".Choices", script.ToString());
        }

        private static void AppendBranch(StringBuilder script, string indent, MockerScope scope, MockerTarget branch)
        {
            string typeName = scope.GetChoicesTypeName(branch);
            List<MockerTarget> children = scope.Tree.GetChildren(branch);

            script.AppendLine($"{indent}/// <summary>Which implementor to use for everything under {scope.GetPath(branch)}.</summary>");
            script.AppendLine($"{indent}public sealed class {typeName}");
            script.AppendLine($"{indent}{{");

            foreach (MockerTarget child in children)
            {
                if (child.Role == MockerRole.Node)
                {
                    string childType = QualifiedChoices(scope, child);

                    script.AppendLine($"{indent}    public {childType} {ScriptNames.Escape(child.Name)} {{ get; }} = new {childType}();");
                }
                else if (child.Role == MockerRole.Component)
                {
                    script.AppendLine($"{indent}    public {scope.GetEnumType(child)} {ScriptNames.Escape(child.Name)} {{ get; set; }}");
                }
            }

            script.AppendLine($"{indent}}}");
        }

        private static string QualifiedChoices(MockerScope scope, MockerTarget branch)
        {
            string name = scope.GetChoicesTypeName(branch);

            return scope.Composite.Type.HasNamespace
                ? ScriptNames.Qualified(scope.Composite.Type.Namespace + "." + name)
                : ScriptNames.Qualified(name);
        }
    }
}
