using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Runs in every assembly that references Mocker and does whatever that assembly calls for: an assembly
    /// holding implementors publishes them, an assembly holding a composite builds the API and the enums,
    /// and an assembly holding neither generates nothing. The roles come from the attributes that are
    /// actually there, so no assembly ever has to be named or configured.
    /// </summary>
    [Generator]
    public class MockerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<MockerTarget> composites = context.FindAllByAttribute(MockerAttributes.Composite, MockerTarget.FromComposite);
            IncrementalValuesProvider<MockerTarget> nodes = context.FindAllByAttribute(MockerAttributes.Node, MockerTarget.FromNode);
            IncrementalValuesProvider<MockerTarget> components = context.FindAllByAttribute(MockerAttributes.Component, MockerTarget.FromComponent);
            IncrementalValuesProvider<MockerTarget> implementors = context.FindAllByAttribute(MockerAttributes.Implementor, MockerTarget.FromImplementor);

            IncrementalValueProvider<ImmutableArray<MockerTarget>> local = ProviderExtensions.CollectAll(composites, nodes, components, implementors);
            IncrementalValueProvider<MockerImports> published = context.CompilationProvider.Select((compilation, _) => ReadImports(compilation));

            context.RegisterSourceOutput(local.Combine(published), (productionContext, batch) =>
            {
                ImmutableArray<MockerTarget> localTargets = batch.Left;
                ImmutableArray<MockerTarget> allTargets = localTargets.AddRange(batch.Right.Targets);

                MockerTree tree = new MockerTree(allTargets);

                MockerValidator.Validate(productionContext, localTargets, allTargets, tree);
                MockerExportWriter.Write(productionContext, localTargets);

                if (batch.Right.IsRoot)
                {
                    MockerEnumWriter.Write(productionContext, allTargets, tree);
                }

                foreach (MockerTarget target in localTargets)
                {
                    if (target.Role != MockerRole.Composite || !target.IsPartial)
                    {
                        continue;
                    }

                    productionContext.AddLocalScript(target.Type, BuildScript(target, allTargets, tree));
                }
            });
        }

        private static MockerImports ReadImports(Compilation compilation)
        {
            List<MockerTarget> published = new List<MockerTarget>();

            foreach (AttributeData attribute in AssemblyScanner.FindAssemblyAttributes(compilation, MockerAttributes.Export))
            {
                MockerTarget target;

                if (MockerTarget.TryFromExport(attribute, out target))
                {
                    published.Add(target);
                }
            }

            published.Sort((left, right) => string.CompareOrdinal(left.Type.FullName, right.Type.FullName));

            return new MockerImports(published.ToImmutableArray(), AssemblyScanner.HasAssemblyAttribute(compilation, MockerAttributes.Root));
        }

        private static string BuildScript(MockerTarget composite, ImmutableArray<MockerTarget> all, MockerTree tree)
        {
            StringBuilder script = new StringBuilder();
            string indent = composite.Type.HasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (composite.Type.HasNamespace)
            {
                script.AppendLine($"namespace {composite.Type.Namespace}");
                script.AppendLine("{");
            }

            script.AppendLine($"{indent}partial class {composite.Type.Name}");
            script.AppendLine($"{indent}{{");
            script.AppendLine($"{indent}    public static void LogComposite()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        UnityEngine.Debug.Log(\"{ScriptWriter.EscapeLiteral(composite.Name)} in {ScriptWriter.EscapeLiteral(composite.Type.AssemblyName)}:\");");

            foreach (string line in BuildBranchLines(composite, all, tree))
            {
                script.AppendLine($"{indent}        UnityEngine.Debug.Log(\"  {ScriptWriter.EscapeLiteral(line)}\");");
            }

            script.AppendLine($"{indent}    }}");
            script.AppendLine($"{indent}}}");

            if (composite.Type.HasNamespace)
            {
                script.AppendLine("}");
            }

            return script.ToString();
        }

        private static List<string> BuildBranchLines(MockerTarget composite, ImmutableArray<MockerTarget> all, MockerTree tree)
        {
            List<string> lines = new List<string>();

            foreach (MockerTarget target in all)
            {
                if (target.Role == MockerRole.Composite)
                {
                    continue;
                }

                string path;
                string rootFullName;

                if (tree.Resolve(target, out path, out rootFullName) != MockerStatus.Resolved)
                {
                    continue;
                }

                if (!string.Equals(rootFullName, composite.Type.FullName, StringComparison.Ordinal))
                {
                    continue;
                }

                lines.Add($"{path} = {target.Role} ({target.Type.Name} from {target.Type.AssemblyName})");
            }

            lines.Sort(StringComparer.Ordinal);

            return lines;
        }
    }
}
