using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the API itself: the property on a composite or node for every child that hangs off it, and
    /// the constructor that fills them. This is generated where the types are declared, because a partial
    /// class can only be completed inside its own assembly.
    /// </summary>
    internal static class MockerApiWriter
    {
        private const string Task = "global::System.Threading.Tasks.Task";
        private const string Token = "global::System.Threading.CancellationToken";

        /// <summary>
        /// Writes a part for every composite and node declared in this assembly.
        /// </summary>
        /// <param name="context">Context the scripts are added to.</param>
        /// <param name="local">Everything declared in this assembly.</param>
        /// <param name="tree">Resolved parent links, used to find each type's children.</param>
        public static void Write(SourceProductionContext context, ImmutableArray<MockerTarget> local, MockerTree tree)
        {
            foreach (MockerTarget target in local)
            {
                bool isBranch = target.Role == MockerRole.Composite || target.Role == MockerRole.Node;

                if (!isBranch || !target.IsPartial)
                {
                    continue;
                }

                context.AddScript(target.Type.FullName + ".Api", BuildScript(target, tree.GetChildren(target)));
            }
        }

        private static string BuildScript(MockerTarget target, List<MockerTarget> children)
        {
            ScriptEmitter emitter = new ScriptEmitter();
            bool isComposite = target.Role == MockerRole.Composite;
            string bases = isComposite ? " : global::System.IDisposable" : string.Empty;

            emitter.Line("// <auto-generated />");

            using (emitter.Namespace(target.Type.Namespace))
            using (emitter.Block($"partial class {target.Type.Name}{bases}"))
            {
                WriteFields(emitter, children);
                WriteConstructor(emitter, target, children);
                WriteProperties(emitter, children, isComposite, target.Type.Name);
                WriteRelease(emitter, children, isComposite);

                if (isComposite)
                {
                    WriteLifecycle(emitter);
                }
            }

            return emitter.ToString();
        }

        private static void WriteFields(ScriptEmitter emitter, List<MockerTarget> children)
        {
            foreach (MockerTarget child in children)
            {
                emitter.Line($"private {ScriptNames.Qualified(child.Type.FullName)} {ScriptNames.ToField(child.Name)};");
            }

            if (children.Count > 0)
            {
                emitter.Line();
            }
        }

        private static void WriteConstructor(ScriptEmitter emitter, MockerTarget target, List<MockerTarget> children)
        {
            List<string> parameters = new List<string>();

            foreach (MockerTarget child in children)
            {
                parameters.Add($"{ScriptNames.Qualified(child.Type.FullName)} {ScriptNames.ToParameter(child.Name)}");
            }

            string accessibility = target.Role == MockerRole.Composite ? "protected" : "public";

            using (emitter.Block($"{accessibility} {target.Type.Name}({string.Join(", ", parameters)})"))
            {
                foreach (MockerTarget child in children)
                {
                    emitter.Line($"{ScriptNames.ToField(child.Name)} = {ScriptNames.ToParameter(child.Name)};");
                }
            }
        }

        private static void WriteProperties(ScriptEmitter emitter, List<MockerTarget> children, bool guardDisposed, string compositeName)
        {
            foreach (MockerTarget child in children)
            {
                emitter.Line();

                using (emitter.Block($"public {ScriptNames.Qualified(child.Type.FullName)} {ScriptNames.Escape(child.Name)}"))
                using (emitter.Block("get"))
                {
                    if (guardDisposed)
                    {
                        using (emitter.Block("if (IsDisposed)"))
                        {
                            emitter.Line($"throw new global::System.ObjectDisposedException(\"{compositeName}\");");
                        }

                        emitter.Line();
                    }

                    emitter.Line($"return {ScriptNames.ToField(child.Name)};");
                }
            }
        }

        private static void WriteRelease(ScriptEmitter emitter, List<MockerTarget> children, bool isComposite)
        {
            emitter.Line();
            emitter.Line("/// <summary>Lets go of everything below, so that disposing frees the tree even while");
            emitter.Line("/// something still holds this object.</summary>");

            using (emitter.Block($"{(isComposite ? "protected" : "internal")} void ReleaseChildren()"))
            {
                foreach (MockerTarget child in children)
                {
                    string field = ScriptNames.ToField(child.Name);

                    if (child.Role == MockerRole.Node)
                    {
                        using (emitter.Block($"if ({field} != null)"))
                        {
                            emitter.Line($"{field}.ReleaseChildren();");
                        }

                        emitter.Line();
                    }

                    emitter.Line($"{field} = null;");
                }
            }
        }
        private static void WriteLifecycle(ScriptEmitter emitter)
        {
            emitter.Line();
            emitter.Line("/// <summary>Set by the generated subclass once this has been disposed.</summary>");
            emitter.Line("protected bool IsDisposed;");
            emitter.Line();
            emitter.Line("/// <summary>Starts every component that needs it, overlapping the ones that do not depend on each other.</summary>");
            emitter.Line($"public abstract {Task} InitializeAsync({Token} cancellationToken);");
            emitter.Line();
            emitter.Line("/// <summary>Tears everything down in reverse of the order it was built.</summary>");
            emitter.Line("public abstract void Dispose();");
            emitter.Line();
            emitter.Line("/// <summary>Runs before anything is initialized. Fields of a derived class are set by now.</summary>");

            using (emitter.Block($"protected virtual {Task} OnBeforeInitialize({Token} cancellationToken)"))
            {
                emitter.Line($"return {Task}.CompletedTask;");
            }

            emitter.Line();
            emitter.Line("/// <summary>Runs once everything has finished initializing.</summary>");

            using (emitter.Block($"protected virtual {Task} OnInitialized({Token} cancellationToken)"))
            {
                emitter.Line($"return {Task}.CompletedTask;");
            }

            emitter.Line();
            emitter.Line("/// <summary>Runs before anything is disposed.</summary>");

            using (emitter.Block("protected virtual void OnBeforeDispose()"))
            {
            }

            emitter.Line();
            emitter.Line("/// <summary>Runs once everything has been disposed.</summary>");

            using (emitter.Block("protected virtual void OnDisposed()"))
            {
            }
        }
    }
}
