using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Detects every Mocker attribute in the compiled assembly, resolves how they hang off each other,
    /// and writes what it found into each composite as a test method.
    /// </summary>
    [Generator]
    public class MockerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<MockerTarget> composites = context.FindAllByAttribute(MockerAttributes.Composite, MockerTarget.FromComposite);
            IncrementalValuesProvider<MockerTarget> nodes = context.FindAllByAttribute(MockerAttributes.Node, MockerTarget.FromNode);
            IncrementalValuesProvider<MockerTarget> components = context.FindAllByAttribute(MockerAttributes.Component, MockerTarget.FromComponent);
            IncrementalValuesProvider<MockerTarget> implementors = context.FindAllByAttribute(MockerAttributes.Implementor, MockerTarget.FromImplementor);

            IncrementalValueProvider<ImmutableArray<MockerTarget>> targets = ProviderExtensions.CollectAll(composites, nodes, components, implementors);

            context.RegisterSourceOutput(targets, (productionContext, found) =>
            {
                MockerTree tree = new MockerTree(found);

                foreach (MockerTarget target in found)
                {
                    if (target.Role != MockerRole.Composite)
                    {
                        continue;
                    }

                    productionContext.AddLocalScript(target.Type, BuildScript(target, found, tree));
                }
            });
        }

        private static string BuildScript(MockerTarget composite, ImmutableArray<MockerTarget> found, MockerTree tree)
        {
            StringBuilder script = new StringBuilder();
            string indent = composite.Type.HasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (composite.Type.HasNamespace)
            {
                script.AppendLine($"namespace {composite.Type.Namespace}");
                script.AppendLine("{");
            }

            script.AppendLine($"{indent}partial class {composite.Type.Name}");
            script.AppendLine($"{indent}{{");
            script.AppendLine($"{indent}    public static void LogComposite()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        UnityEngine.Debug.Log(\"{ScriptWriter.EscapeLiteral(composite.Name)} in {ScriptWriter.EscapeLiteral(composite.Type.AssemblyName)}:\");");

            foreach (string line in BuildBranchLines(composite, found, tree))
            {
                script.AppendLine($"{indent}        UnityEngine.Debug.Log(\"  {ScriptWriter.EscapeLiteral(line)}\");");
            }

            script.AppendLine($"{indent}    }}");
            script.AppendLine($"{indent}}}");

            if (composite.Type.HasNamespace)
            {
                script.AppendLine("}");
            }

            return script.ToString();
        }

        private static List<string> BuildBranchLines(MockerTarget composite, ImmutableArray<MockerTarget> found, MockerTree tree)
        {
            List<string> lines = new List<string>();

            foreach (MockerTarget target in found)
            {
                if (target.Role == MockerRole.Composite)
                {
                    continue;
                }

                if (!string.Equals(tree.GetRootFullName(target), composite.Type.FullName, StringComparison.Ordinal))
                {
                    continue;
                }

                lines.Add($"{tree.GetPath(target)} = {target.Role} ({target.Type.Name})");
            }

            lines.Sort(StringComparer.Ordinal);

            return lines;
        }
    }
}
