using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Publishes everything this assembly declares as assembly level attributes, so an assembly that
    /// references it can rebuild the tree by reading one attribute list instead of walking every type.
    /// </summary>
    internal static class MockerExportWriter
    {
        private const string ScriptName = "MockerExports";

        /// <summary>
        /// Writes the export script, or nothing when this assembly declares no Mocker types.
        /// </summary>
        /// <param name="context">Context the script is added to.</param>
        /// <param name="local">Everything declared in this assembly.</param>
        public static void Write(SourceProductionContext context, ImmutableArray<MockerTarget> local)
        {
            List<string> exports = new List<string>();

            foreach (MockerTarget target in local)
            {
                if (target.IsExternal || target.Type.IsEmpty)
                {
                    continue;
                }

                string parent = target.HasParent ? $"typeof(global::{target.ParentFullName})" : "null";

                exports.Add($"[assembly: reromanlee.Mocker.MockerExport(\"{target.Role}\", typeof(global::{target.Type.FullName}), \"{ScriptWriter.EscapeLiteral(target.Name)}\", {parent})]");
            }

            if (exports.Count == 0)
            {
                return;
            }

            exports.Sort(StringComparer.Ordinal);

            StringBuilder script = new StringBuilder();
            script.AppendLine("// <auto-generated />");

            foreach (string export in exports)
            {
                script.AppendLine(export);
            }

            context.AddScript(ScriptName, script.ToString());
        }
    }
}
