using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the factory and the runnable composite. The factory builds each component on demand and
    /// caches it, so a component that another one needs is built first simply by being asked for, and the
    /// order the calls are written in stops mattering. The composite is generated here rather than beside
    /// the abstract class because only this assembly can see the implementors.
    /// </summary>
    internal static class MockerWiringWriter
    {
        private const string Task = "global::System.Threading.Tasks.Task";
        private const string Token = "global::System.Threading.CancellationToken";
        private const string TokenSource = "global::System.Threading.CancellationTokenSource";
        private const string ObjectList = "global::System.Collections.Generic.List<object>";
        private const string StringList = "global::System.Collections.Generic.List<string>";

        /// <summary>
        /// Writes the factory and the composite subclass for one composite.
        /// </summary>
        /// <param name="context">Context the script is added to.</param>
        /// <param name="scope">The composite and everything under it.</param>
        /// <param name="all">Everything known, for spotting dependencies on another composite.</param>
        public static void Write(SourceProductionContext context, MockerScope scope, ImmutableArray<MockerTarget> all)
        {
            ScriptEmitter emitter = new ScriptEmitter();

            emitter.Line("// <auto-generated />");

            using (emitter.Namespace(scope.Composite.Type.Namespace))
            {
                WriteFactory(context, emitter, scope, all);
                emitter.Line();
                WriteComposite(emitter, scope);
            }

            context.AddScript(scope.Composite.Type.FullName + ".Wiring", emitter.ToString());
        }

        private static string FactoryName(MockerScope scope)
        {
            return scope.Composite.Type.Name + "Factory";
        }

        private static string ChoicesName(MockerScope scope)
        {
            string name = scope.GetChoicesTypeName(scope.Composite);

            return scope.Composite.Type.HasNamespace
                ? ScriptNames.Qualified(scope.Composite.Type.Namespace + "." + name)
                : ScriptNames.Qualified(name);
        }

        private static void WriteFactory(SourceProductionContext context, ScriptEmitter emitter, MockerScope scope, ImmutableArray<MockerTarget> all)
        {
            using (emitter.Block($"internal sealed class {FactoryName(scope)}"))
            {
                emitter.Line($"private readonly {ChoicesName(scope)} _choices;");
                emitter.Line("private readonly global::reromanlee.Mocker.Dependencies _dependencies;");
                emitter.Line($"private readonly {StringList} _resolving = new {StringList}();");
                emitter.Line($"private readonly {ObjectList} _created = new {ObjectList}();");
                emitter.Line();

                foreach (MockerTarget node in scope.Branches)
                {
                    if (node.Role == MockerRole.Node)
                    {
                        emitter.Line($"private {ScriptNames.Qualified(node.Type.FullName)} {scope.GetFieldId(node)};");
                    }
                }

                foreach (MockerTarget component in scope.Components)
                {
                    emitter.Line($"private {ScriptNames.Qualified(component.Type.FullName)} {scope.GetFieldId(component)};");

                    if (scope.NeedsInitialization(component))
                    {
                        emitter.Line($"private {Task} _init{scope.GetFieldId(component)};");
                    }
                }

                emitter.Line();

                using (emitter.Block($"public {FactoryName(scope)}({ChoicesName(scope)} choices, global::reromanlee.Mocker.Dependencies dependencies)"))
                {
                    emitter.Line($"_choices = choices ?? new {ChoicesName(scope)}();");
                    emitter.Line("_dependencies = dependencies ?? new global::reromanlee.Mocker.Dependencies();");
                }

                emitter.Line();
                emitter.Line("/// <summary>Everything that was built, in the order it was built.</summary>");

                using (emitter.Block($"public {ObjectList} Created"))
                {
                    emitter.Line("get { return _created; }");
                }

                foreach (MockerTarget node in scope.Branches)
                {
                    if (node.Role == MockerRole.Node)
                    {
                        WriteNodeFactory(emitter, scope, node);
                    }
                }

                foreach (MockerTarget component in scope.Components)
                {
                    WriteComponentFactory(context, emitter, scope, component, all);
                    WriteComponentInitializer(emitter, scope, component);
                }

                WriteRelease(emitter, scope);
                WriteResolveGuards(emitter);
            }
        }

        private static void WriteNodeFactory(ScriptEmitter emitter, MockerScope scope, MockerTarget node)
        {
            string field = scope.GetFieldId(node);
            List<string> arguments = new List<string>();

            foreach (MockerTarget child in scope.Tree.GetChildren(node))
            {
                arguments.Add($"Create{scope.GetMemberId(child)}()");
            }

            emitter.Line();

            using (emitter.Block($"public {ScriptNames.Qualified(node.Type.FullName)} Create{scope.GetMemberId(node)}()"))
            {
                using (emitter.Block($"if ({field} != null)"))
                {
                    emitter.Line($"return {field};");
                }

                emitter.Line();
                emitter.Line($"{field} = new {ScriptNames.Qualified(node.Type.FullName)}({string.Join(", ", arguments)});");
                emitter.Line($"_created.Add({field});");
                emitter.Line();
                emitter.Line($"return {field};");
            }
        }

        private static void WriteComponentFactory(SourceProductionContext context, ScriptEmitter emitter, MockerScope scope, MockerTarget component, ImmutableArray<MockerTarget> all)
        {
            string field = scope.GetFieldId(component);

            emitter.Line();

            using (emitter.Block($"public {ScriptNames.Qualified(component.Type.FullName)} Create{scope.GetMemberId(component)}()"))
            {
                using (emitter.Block($"if ({field} != null)"))
                {
                    emitter.Line($"return {field};");
                }

                emitter.Line();
                emitter.Line($"BeginResolve(\"{scope.GetPath(component)}\");");
                emitter.Line();

                using (emitter.Block($"switch ({scope.GetChoicesAccessor(component)})"))
                {
                    foreach (MockerTarget implementor in scope.GetImplementors(component))
                    {
                        emitter.Line($"case {scope.GetEnumType(component)}.{implementor.Name}:");
                        emitter.Line($"    {field} = new {ScriptNames.Qualified(implementor.Type.FullName)}({BuildArguments(context, scope, component, implementor, all)});");
                        emitter.Line("    break;");
                        emitter.Line();
                    }

                    emitter.Line("default:");
                    emitter.Line($"    {field} = new {scope.GetMockType(component)}();");
                    emitter.Line("    break;");
                }

                emitter.Line();
                emitter.Line("EndResolve();");
                emitter.Line($"_created.Add({field});");
                emitter.Line();
                emitter.Line($"return {field};");
            }
        }

        private static string BuildArguments(SourceProductionContext context, MockerScope scope, MockerTarget component, MockerTarget implementor, ImmutableArray<MockerTarget> all)
        {
            List<string> arguments = new List<string>();

            foreach (string parameterType in implementor.Details.ParameterTypes)
            {
                MockerTarget dependency;

                if (scope.TryGetComponent(parameterType, out dependency))
                {
                    arguments.Add($"Create{scope.GetMemberId(dependency)}()");

                    continue;
                }

                ReportForeignComponent(context, scope, implementor, parameterType, all);

                arguments.Add($"_dependencies.Require<{parameterType}>(\"{scope.GetPath(component)}\", \"{implementor.Type.Name}\")");
            }

            return string.Join(", ", arguments);
        }

        private static void ReportForeignComponent(SourceProductionContext context, MockerScope scope, MockerTarget implementor, string parameterType, ImmutableArray<MockerTarget> all)
        {
            foreach (MockerTarget candidate in all)
            {
                if (candidate.Role != MockerRole.Component)
                {
                    continue;
                }

                if (!string.Equals(ScriptNames.Qualified(candidate.Type.FullName), parameterType, StringComparison.Ordinal))
                {
                    continue;
                }

                string owner;
                string path;

                if (scope.Tree.Resolve(candidate, out path, out owner) == MockerStatus.Resolved)
                {
                    context.Report(MockerDiagnostics.ForeignComponent, implementor.Location, implementor.Type.Name, candidate.Type.Name, owner);
                }

                return;
            }
        }

        private static void WriteComponentInitializer(ScriptEmitter emitter, MockerScope scope, MockerTarget component)
        {
            string member = scope.GetMemberId(component);
            string field = scope.GetFieldId(component);

            emitter.Line();

            if (!scope.NeedsInitialization(component))
            {
                emitter.Line("/// <summary>Nothing under this initializes, so there is nothing to wait for.</summary>");

                using (emitter.Block($"public {Task} Initialize{member}Async({Token} cancellationToken)"))
                {
                    emitter.Line($"return {Task}.CompletedTask;");
                }

                return;
            }

            using (emitter.Block($"public {Task} Initialize{member}Async({Token} cancellationToken)"))
            {
                using (emitter.Block($"if (_init{field} == null)"))
                {
                    emitter.Line($"_init{field} = Run{member}Async(cancellationToken);");
                }

                emitter.Line();
                emitter.Line($"return _init{field};");
            }

            emitter.Line();

            using (emitter.Block($"private async {Task} Run{member}Async({Token} cancellationToken)"))
            {
                using (emitter.Block($"switch ({scope.GetChoicesAccessor(component)})"))
                {
                    foreach (MockerTarget implementor in scope.GetImplementors(component))
                    {
                        emitter.Line($"case {scope.GetEnumType(component)}.{implementor.Name}:");

                        foreach (string parameterType in implementor.Details.ParameterTypes)
                        {
                            MockerTarget dependency;

                            if (scope.TryGetComponent(parameterType, out dependency))
                            {
                                emitter.Line($"    await Initialize{scope.GetMemberId(dependency)}Async(cancellationToken);");
                            }
                        }

                        if (implementor.Details.IsAsyncInitializable)
                        {
                            emitter.Line($"    await (({ScriptNames.Qualified(implementor.Type.FullName)}){field}).InitializeAsync(cancellationToken);");
                        }

                        emitter.Line("    break;");
                        emitter.Line();
                    }

                    emitter.Line("default:");
                    emitter.Line("    break;");
                }
            }
        }

        private static void WriteRelease(ScriptEmitter emitter, MockerScope scope)
        {
            emitter.Line();
            emitter.Line("/// <summary>Drops every reference held here, so disposing releases what was built even");
            emitter.Line("/// if something is still holding the composite itself.</summary>");

            using (emitter.Block("public void Release()"))
            {
                emitter.Line("_created.Clear();");

                foreach (MockerTarget node in scope.Branches)
                {
                    if (node.Role == MockerRole.Node)
                    {
                        emitter.Line($"{scope.GetFieldId(node)} = null;");
                    }
                }

                foreach (MockerTarget component in scope.Components)
                {
                    emitter.Line($"{scope.GetFieldId(component)} = null;");

                    if (scope.NeedsInitialization(component))
                    {
                        emitter.Line($"_init{scope.GetFieldId(component)} = null;");
                    }
                }
            }
        }
        private static void WriteResolveGuards(ScriptEmitter emitter)
        {
            emitter.Line();

            using (emitter.Block("private void BeginResolve(string path)"))
            {
                using (emitter.Block("if (_resolving.Contains(path))"))
                {
                    emitter.Line("_resolving.Add(path);");
                    emitter.Line("throw new global::System.InvalidOperationException(\"Cycle: \" + string.Join(\" -> \", _resolving.ToArray()) + \". One of these has to stop taking the other in its constructor.\");");
                }

                emitter.Line();
                emitter.Line("_resolving.Add(path);");
            }

            emitter.Line();

            using (emitter.Block("private void EndResolve()"))
            {
                emitter.Line("_resolving.RemoveAt(_resolving.Count - 1);");
            }
        }

        private static void WriteComposite(ScriptEmitter emitter, MockerScope scope)
        {
            string composite = scope.Composite.Type.Name;
            string factory = FactoryName(scope);
            string choices = ChoicesName(scope);
            List<string> baseArguments = new List<string>();

            foreach (MockerTarget child in scope.Tree.GetChildren(scope.Composite))
            {
                baseArguments.Add($"factory.Create{scope.GetMemberId(child)}()");
            }

            emitter.Line($"/// <summary>{composite} with the implementors this assembly can see. This is the one to construct.</summary>");

            using (emitter.Block($"public class {composite}Composite : {ScriptNames.Qualified(scope.Composite.Type.FullName)}"))
            {
                emitter.Line($"private readonly {factory} _factory;");
                emitter.Line($"private readonly {choices} _choices;");
                emitter.Line($"private readonly {TokenSource} _cancellation = new {TokenSource}();");
                emitter.Line("private int _state;");
                emitter.Line();

                using (emitter.Block($"public {composite}Composite({choices} choices, global::reromanlee.Mocker.Dependencies dependencies)",
                    $": this(new {factory}(choices, dependencies), choices)"))
                {
                }

                emitter.Line();

                using (emitter.Block($"private {composite}Composite({factory} factory, {choices} choices)",
                    $": base({string.Join(", ", baseArguments)})"))
                {
                    emitter.Line("_factory = factory;");
                    emitter.Line($"_choices = choices ?? new {choices}();");
                }

                emitter.Line();
                emitter.Line("/// <summary>The choices this was built from, so code can branch on what it actually got.</summary>");

                using (emitter.Block($"public {choices} Choices"))
                {
                    emitter.Line("get { return _choices; }");
                }

                WriteInitialize(emitter, scope, composite);
                WriteDispose(emitter, composite);
            }
        }

        private static void WriteInitialize(ScriptEmitter emitter, MockerScope scope, string composite)
        {
            emitter.Line();

            using (emitter.Block($"public override async {Task} InitializeAsync({Token} cancellationToken)"))
            {
                using (emitter.Block("if (_state == 3)"))
                {
                    emitter.Line($"throw new global::System.ObjectDisposedException(\"{composite}\");");
                }

                emitter.Line();

                using (emitter.Block("if (_state != 0)"))
                {
                    emitter.Line($"throw new global::System.InvalidOperationException(\"{composite} was already initialized.\");");
                }

                emitter.Line();
                emitter.Line("_state = 1;");
                emitter.Line();

                using (emitter.Block($"using ({TokenSource} linked = {TokenSource}.CreateLinkedTokenSource(cancellationToken, _cancellation.Token))"))
                {
                    emitter.Line("await OnBeforeInitialize(linked.Token);");
                    emitter.Line();

                    List<string> started = new List<string>();

                    foreach (MockerTarget component in scope.Components)
                    {
                        if (!scope.NeedsInitialization(component))
                        {
                            continue;
                        }

                        string local = "start" + scope.GetMemberId(component);

                        started.Add(local);
                        emitter.Line($"{Task} {local} = _factory.Initialize{scope.GetMemberId(component)}Async(linked.Token);");
                    }

                    if (started.Count > 0)
                    {
                        emitter.Line();
                    }

                    foreach (string local in started)
                    {
                        emitter.Line($"await {local};");
                    }

                    if (started.Count > 0)
                    {
                        emitter.Line();
                    }

                    emitter.Line("await OnInitialized(linked.Token);");
                }

                emitter.Line();
                emitter.Line("_state = 2;");
            }
        }

        private static void WriteDispose(ScriptEmitter emitter, string composite)
        {
            emitter.Line();

            using (emitter.Block("public override void Dispose()"))
            {
                using (emitter.Block("if (_state == 3)"))
                {
                    emitter.Line("return;");
                }

                emitter.Line();
                emitter.Line("_state = 3;");
                emitter.Line("IsDisposed = true;");
                emitter.Line("_cancellation.Cancel();");
                emitter.Line("OnBeforeDispose();");
                emitter.Line();
                emitter.Line("global::System.Collections.Generic.List<global::System.Exception> failures = null;");
                emitter.Line($"{ObjectList} created = _factory.Created;");
                emitter.Line();

                using (emitter.Block("for (int index = created.Count - 1; index >= 0; index--)"))
                {
                    emitter.Line("global::System.IDisposable disposable = created[index] as global::System.IDisposable;");
                    emitter.Line();

                    using (emitter.Block("if (disposable == null)"))
                    {
                        emitter.Line("continue;");
                    }

                    emitter.Line();

                    using (emitter.Block("try"))
                    {
                        emitter.Line("disposable.Dispose();");
                    }

                    using (emitter.Block("catch (global::System.Exception exception)"))
                    {
                        using (emitter.Block("if (failures == null)"))
                        {
                            emitter.Line("failures = new global::System.Collections.Generic.List<global::System.Exception>();");
                        }

                        emitter.Line();
                        emitter.Line("failures.Add(exception);");
                    }
                }

                emitter.Line();
                emitter.Line("_cancellation.Dispose();");
                emitter.Line("_factory.Release();");
                emitter.Line("ReleaseChildren();");
                emitter.Line("OnDisposed();");
                emitter.Line();

                using (emitter.Block("if (failures != null)"))
                {
                    emitter.Line($"throw new global::System.AggregateException(\"{composite} did not dispose cleanly.\", failures);");
                }
            }
        }
    }
}
