using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the do-nothing implementation used when a component is set to None. It is generated next to
    /// the component, because it needs nothing but the interface, and it is partial so that a component
    /// that needs its mock to actually hold something can have that written by hand.
    /// </summary>
    internal static class MockerMockWriter
    {
        private const string TaskType = "global::System.Threading.Tasks.Task";

        /// <summary>
        /// Builds the mock for the component the attribute was found on.
        /// </summary>
        /// <param name="context">The component that was found.</param>
        /// <param name="cancellationToken">Cancels a long generation pass.</param>
        /// <returns>The mock, or the member that stopped one being written.</returns>
        public static MockScript Build(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
        {
            INamedTypeSymbol component = context.TargetSymbol as INamedTypeSymbol;
            ScriptLocation location = ScriptLocation.From(context.TargetNode);

            if (component == null || component.TypeKind != TypeKind.Interface)
            {
                return default(MockScript);
            }

            TypeTarget type = TypeTarget.From(component);
            string mockName = ScriptNames.TrimInterfacePrefix(type.Name) + "Mock";
            StringBuilder members = new StringBuilder();
            string indent = type.HasNamespace ? "        " : "    ";

            foreach (ISymbol member in GetAllMembers(component))
            {
                cancellationToken.ThrowIfCancellationRequested();

                string unsupported = AppendMember(members, indent, member);

                if (unsupported != null)
                {
                    return new MockScript(string.Empty, string.Empty, unsupported, location);
                }
            }

            return new MockScript(type.FullName + ".Mock", BuildScript(type, mockName, members.ToString()), string.Empty, location);
        }

        private static IEnumerable<ISymbol> GetAllMembers(INamedTypeSymbol component)
        {
            foreach (ISymbol member in component.GetMembers())
            {
                yield return member;
            }

            foreach (INamedTypeSymbol inherited in component.AllInterfaces)
            {
                foreach (ISymbol member in inherited.GetMembers())
                {
                    yield return member;
                }
            }
        }

        private static string BuildScript(TypeTarget type, string mockName, string members)
        {
            StringBuilder script = new StringBuilder();
            string indent = type.HasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (type.HasNamespace)
            {
                script.AppendLine($"namespace {type.Namespace}");
                script.AppendLine("{");
            }

            script.AppendLine($"{indent}public partial class {mockName} : {ScriptNames.Qualified(type.FullName)}");
            script.AppendLine($"{indent}{{");
            script.Append(members);
            script.AppendLine($"{indent}}}");

            if (type.HasNamespace)
            {
                script.AppendLine("}");
            }

            return script.ToString();
        }

        private static string AppendMember(StringBuilder members, string indent, ISymbol member)
        {
            IPropertySymbol property = member as IPropertySymbol;

            if (property != null)
            {
                return property.Parameters.Length > 0 ? property.Name : AppendProperty(members, indent, property);
            }

            IEventSymbol eventSymbol = member as IEventSymbol;

            if (eventSymbol != null)
            {
                members.AppendLine($"{indent}public event {Display(eventSymbol.Type)} {eventSymbol.Name} {{ add {{ }} remove {{ }} }}");

                return null;
            }

            IMethodSymbol method = member as IMethodSymbol;

            if (method != null && method.MethodKind == MethodKind.Ordinary)
            {
                return AppendMethod(members, indent, method);
            }

            return null;
        }

        private static string AppendProperty(StringBuilder members, string indent, IPropertySymbol property)
        {
            string body = string.Empty;

            if (property.GetMethod != null)
            {
                string returned = GetReturnExpression(property.Type);

                if (returned == null)
                {
                    return property.Name;
                }

                body += $" get {{ return {returned}; }}";
            }

            if (property.SetMethod != null)
            {
                body += " set { }";
            }

            members.AppendLine($"{indent}public {Display(property.Type)} {property.Name} {{{body} }}");

            return null;
        }

        private static string AppendMethod(StringBuilder members, string indent, IMethodSymbol method)
        {
            string returnType = method.ReturnsVoid ? "void" : Display(method.ReturnType);
            string returned = method.ReturnsVoid ? string.Empty : GetReturnExpression(method.ReturnType);

            if (!method.ReturnsVoid && returned == null)
            {
                return method.Name;
            }

            List<string> parameters = new List<string>();

            foreach (IParameterSymbol parameter in method.Parameters)
            {
                parameters.Add($"{GetModifier(parameter)}{Display(parameter.Type)} {ScriptNames.Escape(parameter.Name)}");
            }

            string typeParameters = method.TypeParameters.Length == 0
                ? string.Empty
                : "<" + string.Join(", ", method.TypeParameters.Select(parameter => parameter.Name)) + ">";

            members.AppendLine($"{indent}public {returnType} {method.Name}{typeParameters}({string.Join(", ", parameters)}){GetConstraints(method)}");
            members.AppendLine($"{indent}{{");

            foreach (IParameterSymbol parameter in method.Parameters)
            {
                if (parameter.RefKind == RefKind.Out)
                {
                    members.AppendLine($"{indent}    {ScriptNames.Escape(parameter.Name)} = default({Display(parameter.Type)});");
                }
            }

            if (!method.ReturnsVoid)
            {
                members.AppendLine($"{indent}    return {returned};");
            }

            members.AppendLine($"{indent}}}");

            return null;
        }

        private static string GetModifier(IParameterSymbol parameter)
        {
            string modifier = string.Empty;

            switch (parameter.RefKind)
            {
                case RefKind.Ref:
                    modifier = "ref ";
                    break;

                case RefKind.Out:
                    modifier = "out ";
                    break;

                case RefKind.In:
                    modifier = "in ";
                    break;
            }

            return parameter.IsParams ? "params " + modifier : modifier;
        }

        private static string GetConstraints(IMethodSymbol method)
        {
            StringBuilder constraints = new StringBuilder();

            foreach (ITypeParameterSymbol parameter in method.TypeParameters)
            {
                List<string> parts = new List<string>();

                if (parameter.HasReferenceTypeConstraint)
                {
                    parts.Add("class");
                }

                if (parameter.HasValueTypeConstraint)
                {
                    parts.Add("struct");
                }

                if (parameter.HasUnmanagedTypeConstraint)
                {
                    parts.Add("unmanaged");
                }

                foreach (ITypeSymbol constraint in parameter.ConstraintTypes)
                {
                    parts.Add(Display(constraint));
                }

                if (parameter.HasConstructorConstraint)
                {
                    parts.Add("new()");
                }

                if (parts.Count > 0)
                {
                    constraints.Append($" where {parameter.Name} : {string.Join(", ", parts)}");
                }
            }

            return constraints.ToString();
        }

        private static string GetReturnExpression(ITypeSymbol returnType)
        {
            string displayed = Display(returnType);

            if (displayed == TaskType)
            {
                return TaskType + ".CompletedTask";
            }

            INamedTypeSymbol named = returnType as INamedTypeSymbol;
            bool isGenericTask = named != null
                && named.TypeArguments.Length == 1
                && Display(named.OriginalDefinition).StartsWith(TaskType + "<", StringComparison.Ordinal);

            if (isGenericTask)
            {
                return $"{TaskType}.FromResult(default({Display(named.TypeArguments[0])}))";
            }

            // Something awaitable that is a value type is already completed when it is default, which covers
            // ValueTask and UniTask. A reference type would be null, and awaiting null throws.
            if (returnType.IsReferenceType && IsAwaitable(returnType))
            {
                return null;
            }

            return $"default({displayed})";
        }

        private static bool IsAwaitable(ITypeSymbol type)
        {
            return type.GetMembers("GetAwaiter").OfType<IMethodSymbol>().Any(method => method.Parameters.Length == 0);
        }

        private static string Display(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
    }
}
