using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the do-nothing implementation used when a component is set to None. It is generated next to
    /// the component, because it needs nothing but the interface, and it is partial so that a component
    /// that needs its mock to actually hold something can have that written by hand.
    /// </summary>
    internal static class MockerMockWriter
    {
        private const string TaskType = "global::System.Threading.Tasks.Task";
        private const string AwaitableType = "global::UnityEngine.Awaitable";
        private const string CompletionSource = "global::UnityEngine.AwaitableCompletionSource";

        /// <summary>
        /// Builds the mock for the component the attribute was found on.
        /// </summary>
        /// <param name="context">The component that was found.</param>
        /// <param name="cancellationToken">Cancels a long generation pass.</param>
        /// <returns>The mock, or the member that stopped one being written.</returns>
        public static MockScript Build(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
        {
            INamedTypeSymbol component = context.TargetSymbol as INamedTypeSymbol;
            ScriptLocation location = ScriptLocation.From(context.TargetNode);

            if (component == null || component.TypeKind != TypeKind.Interface)
            {
                return default(MockScript);
            }

            TypeTarget type = TypeTarget.From(component);
            string mockName = ScriptNames.TrimInterfacePrefix(type.Name) + "Mock";
            ScriptEmitter emitter = new ScriptEmitter();
            MockState state = new MockState();
            string unsupported = null;

            emitter.Line("// <auto-generated />");

            using (emitter.Namespace(type.Namespace))
            {
                emitter.Line($"/// <summary>Does nothing, so that a {type.Name} nobody provided still answers every call.</summary>");

                using (emitter.Block($"public partial class {mockName} : {ScriptNames.Qualified(type.FullName)}"))
                {
                    foreach (ISymbol member in GetAllMembers(component))
                    {
                        cancellationToken.ThrowIfCancellationRequested();

                        unsupported = WriteMember(emitter, state, member);

                        if (unsupported != null)
                        {
                            break;
                        }
                    }

                    WriteAwaitableHelpers(emitter, state);
                }
            }

            if (unsupported != null)
            {
                return new MockScript(string.Empty, string.Empty, unsupported, location);
            }

            return new MockScript(type.FullName + ".Mock", emitter.ToString(), string.Empty, location);
        }

        private static IEnumerable<ISymbol> GetAllMembers(INamedTypeSymbol component)
        {
            foreach (ISymbol member in component.GetMembers())
            {
                yield return member;
            }

            foreach (INamedTypeSymbol inherited in component.AllInterfaces)
            {
                foreach (ISymbol member in inherited.GetMembers())
                {
                    yield return member;
                }
            }
        }

        private static string WriteMember(ScriptEmitter emitter, MockState state, ISymbol member)
        {
            IPropertySymbol property = member as IPropertySymbol;

            if (property != null)
            {
                return WriteProperty(emitter, state, property);
            }

            IEventSymbol eventSymbol = member as IEventSymbol;

            if (eventSymbol != null)
            {
                emitter.Line($"public event {Display(eventSymbol.Type)} {eventSymbol.Name} {{ add {{ }} remove {{ }} }}");

                return null;
            }

            IMethodSymbol method = member as IMethodSymbol;

            if (method != null && method.MethodKind == MethodKind.Ordinary)
            {
                return WriteMethod(emitter, state, method);
            }

            return null;
        }

        private static string WriteProperty(ScriptEmitter emitter, MockState state, IPropertySymbol property)
        {
            string body = string.Empty;

            if (property.GetMethod != null)
            {
                string returned = GetReturnExpression(property.Type, state);

                if (returned == null)
                {
                    return property.Name;
                }

                body += $" get {{ return {returned}; }}";
            }

            if (property.SetMethod != null)
            {
                body += " set { }";
            }

            emitter.Line($"public {Display(property.Type)} {GetPropertyName(property)} {{{body} }}");

            return null;
        }

        private static string GetPropertyName(IPropertySymbol property)
        {
            if (property.Parameters.Length == 0)
            {
                return property.Name;
            }

            List<string> parameters = new List<string>();

            foreach (IParameterSymbol parameter in property.Parameters)
            {
                parameters.Add($"{GetModifier(parameter)}{Display(parameter.Type)} {ScriptNames.Escape(parameter.Name)}");
            }

            return $"this[{string.Join(", ", parameters)}]";
        }

        private static void WriteAwaitableHelpers(ScriptEmitter emitter, MockState state)
        {
            if (state.NeedsAwaitable)
            {
                emitter.Line();

                using (emitter.Block($"private static {AwaitableType} CompletedAwaitable()"))
                {
                    emitter.Line($"{CompletionSource} source = new {CompletionSource}();");
                    emitter.Line("source.SetResult();");
                    emitter.Line();
                    emitter.Line("return source.Awaitable;");
                }
            }

            if (state.NeedsAwaitableResult)
            {
                emitter.Line();

                using (emitter.Block($"private static {AwaitableType}<TResult> CompletedAwaitable<TResult>(TResult result)"))
                {
                    emitter.Line($"{CompletionSource}<TResult> source = new {CompletionSource}<TResult>();");
                    emitter.Line("source.SetResult(result);");
                    emitter.Line();
                    emitter.Line("return source.Awaitable;");
                }
            }
        }

        private sealed class MockState
        {
            public bool NeedsAwaitable;
            public bool NeedsAwaitableResult;
        }

        private static string WriteMethod(ScriptEmitter emitter, MockState state, IMethodSymbol method)
        {
            string returnType = method.ReturnsVoid ? "void" : Display(method.ReturnType);
            string returned = method.ReturnsVoid ? string.Empty : GetReturnExpression(method.ReturnType, state);

            if (!method.ReturnsVoid && returned == null)
            {
                return method.Name;
            }

            List<string> parameters = new List<string>();

            foreach (IParameterSymbol parameter in method.Parameters)
            {
                parameters.Add($"{GetModifier(parameter)}{Display(parameter.Type)} {ScriptNames.Escape(parameter.Name)}");
            }

            string typeParameters = method.TypeParameters.Length == 0
                ? string.Empty
                : "<" + string.Join(", ", method.TypeParameters.Select(parameter => parameter.Name)) + ">";

            using (emitter.Block($"public {returnType} {method.Name}{typeParameters}({string.Join(", ", parameters)}){GetConstraints(method)}"))
            {
                foreach (IParameterSymbol parameter in method.Parameters)
                {
                    if (parameter.RefKind == RefKind.Out)
                    {
                        emitter.Line($"{ScriptNames.Escape(parameter.Name)} = default({Display(parameter.Type)});");
                    }
                }

                if (!method.ReturnsVoid)
                {
                    emitter.Line($"return {returned};");
                }
            }

            return null;
        }

        private static string GetModifier(IParameterSymbol parameter)
        {
            string modifier = string.Empty;

            switch (parameter.RefKind)
            {
                case RefKind.Ref:
                    modifier = "ref ";
                    break;

                case RefKind.Out:
                    modifier = "out ";
                    break;

                case RefKind.In:
                    modifier = "in ";
                    break;
            }

            return parameter.IsParams ? "params " + modifier : modifier;
        }

        private static string GetConstraints(IMethodSymbol method)
        {
            List<string> constraints = new List<string>();

            foreach (ITypeParameterSymbol parameter in method.TypeParameters)
            {
                List<string> parts = new List<string>();

                if (parameter.HasReferenceTypeConstraint)
                {
                    parts.Add("class");
                }

                if (parameter.HasValueTypeConstraint)
                {
                    parts.Add("struct");
                }

                if (parameter.HasUnmanagedTypeConstraint)
                {
                    parts.Add("unmanaged");
                }

                foreach (ITypeSymbol constraint in parameter.ConstraintTypes)
                {
                    parts.Add(Display(constraint));
                }

                if (parameter.HasConstructorConstraint)
                {
                    parts.Add("new()");
                }

                if (parts.Count > 0)
                {
                    constraints.Add($" where {parameter.Name} : {string.Join(", ", parts)}");
                }
            }

            return string.Join(string.Empty, constraints);
        }

        private static string GetReturnExpression(ITypeSymbol returnType, MockState state)
        {
            string displayed = Display(returnType);

            if (displayed == TaskType)
            {
                return TaskType + ".CompletedTask";
            }

            if (displayed == AwaitableType)
            {
                state.NeedsAwaitable = true;

                return "CompletedAwaitable()";
            }

            INamedTypeSymbol named = returnType as INamedTypeSymbol;
            bool isGeneric = named != null && named.TypeArguments.Length == 1;
            string definition = isGeneric ? Display(named.OriginalDefinition) : string.Empty;

            if (isGeneric && definition.StartsWith(TaskType + "<", StringComparison.Ordinal))
            {
                return $"{TaskType}.FromResult(default({Display(named.TypeArguments[0])}))";
            }

            if (isGeneric && definition.StartsWith(AwaitableType + "<", StringComparison.Ordinal))
            {
                state.NeedsAwaitableResult = true;

                return $"CompletedAwaitable(default({Display(named.TypeArguments[0])}))";
            }

            // Something awaitable that is a value type is already completed when it is default, which covers
            // ValueTask and UniTask. A reference type would be null, and awaiting null throws.
            if (returnType.IsReferenceType && IsAwaitable(returnType))
            {
                return null;
            }

            return $"default({displayed})";
        }

        private static bool IsAwaitable(ITypeSymbol type)
        {
            return type.GetMembers("GetAwaiter").OfType<IMethodSymbol>().Any(method => method.Parameters.Length == 0);
        }

        private static string Display(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
    }
}
