using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes one enum per component listing every implementor of it. This only runs in the assembly
    /// marked as the composition root, because that is the only assembly that sees both sides: an
    /// implementor must reference the assembly declaring its component, so that assembly can never
    /// reference the implementors back, and only a third assembly downstream of both sees everything.
    /// </summary>
    internal static class MockerEnumWriter
    {
        private const string NameSuffix = "Implementor";

        /// <summary>
        /// Member every enum starts with, so that the default value means nothing was selected rather
        /// than whichever implementor happens to sort first.
        /// </summary>
        public const string NoneMember = "None";

        /// <summary>
        /// Writes an enum for every component that belongs to a composite.
        /// </summary>
        /// <param name="context">Context the scripts are added to.</param>
        /// <param name="all">Everything known, declared here and published by referenced assemblies.</param>
        /// <param name="tree">Resolved parent links.</param>
        /// <param name="imports">The root marker, which says which composites this assembly owns.</param>
        public static void Write(SourceProductionContext context, ImmutableArray<MockerTarget> all, MockerTree tree, MockerImports imports)
        {
            foreach (MockerTarget component in all)
            {
                string path;
                string rootFullName;

                if (component.Role != MockerRole.Component || tree.Resolve(component, out path, out rootFullName) != MockerStatus.Resolved)
                {
                    continue;
                }

                if (!imports.Owns(rootFullName))
                {
                    continue;
                }

                context.AddScript(component.Type.FullName + "." + NameSuffix, BuildScript(component, GetImplementorNames(component, all)));
            }
        }

        private static List<string> GetImplementorNames(MockerTarget component, ImmutableArray<MockerTarget> all)
        {
            List<string> names = new List<string>();

            foreach (MockerTarget target in all)
            {
                if (target.Role == MockerRole.Implementor && string.Equals(target.ParentFullName, component.Type.FullName, StringComparison.Ordinal))
                {
                    names.Add(target.Name);
                }
            }

            names.Sort(StringComparer.Ordinal);

            return names;
        }

        private static string BuildScript(MockerTarget component, List<string> implementorNames)
        {
            ScriptEmitter emitter = new ScriptEmitter();

            emitter.Line("// <auto-generated />");

            using (emitter.Namespace(component.Type.Namespace))
            {
                emitter.Line($"/// <summary>Which implementation of {component.Type.Name} to build.</summary>");

                using (emitter.Block($"public enum {ScriptNames.TrimInterfacePrefix(component.Type.Name)}{NameSuffix}"))
                {
                    emitter.Line($"/// <summary>Use the generated mock, which does nothing and gets in nobody's way.</summary>");
                    emitter.Line($"{NoneMember} = 0{(implementorNames.Count == 0 ? string.Empty : ",")}");

                    for (int index = 0; index < implementorNames.Count; index++)
                    {
                        bool isLast = index == implementorNames.Count - 1;

                        emitter.Line($"{implementorNames[index]}{(isLast ? string.Empty : ",")}");
                    }
                }
            }

            return emitter.ToString();
        }
    }
}
