using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the factory and the runnable composite. The factory builds each component on demand and
    /// caches it, so a component that another one needs is built first simply by being asked for, and the
    /// order the calls are written in stops mattering. The composite is generated here rather than beside
    /// the abstract class because only this assembly can see the implementors.
    /// </summary>
    internal static class MockerWiringWriter
    {
        private const string Task = "global::System.Threading.Tasks.Task";
        private const string Token = "global::System.Threading.CancellationToken";

        /// <summary>
        /// Writes the factory and the composite subclass for one composite.
        /// </summary>
        /// <param name="context">Context the script is added to.</param>
        /// <param name="scope">The composite and everything under it.</param>
        /// <param name="all">Everything known, for spotting dependencies on another composite.</param>
        public static void Write(SourceProductionContext context, MockerScope scope, ImmutableArray<MockerTarget> all)
        {
            StringBuilder script = new StringBuilder();
            bool hasNamespace = scope.Composite.Type.HasNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (hasNamespace)
            {
                script.AppendLine($"namespace {scope.Composite.Type.Namespace}");
                script.AppendLine("{");
            }

            AppendFactory(context, script, indent, scope, all);
            script.AppendLine();
            AppendComposite(script, indent, scope);

            if (hasNamespace)
            {
                script.AppendLine("}");
            }

            context.AddScript(scope.Composite.Type.FullName + ".Wiring", script.ToString());
        }

        private static string FactoryName(MockerScope scope)
        {
            return scope.Composite.Type.Name + "Factory";
        }

        private static string ChoicesName(MockerScope scope)
        {
            string name = scope.GetChoicesTypeName(scope.Composite);

            return scope.Composite.Type.HasNamespace
                ? ScriptNames.Qualified(scope.Composite.Type.Namespace + "." + name)
                : ScriptNames.Qualified(name);
        }

        private static void AppendFactory(SourceProductionContext context, StringBuilder script, string indent, MockerScope scope, ImmutableArray<MockerTarget> all)
        {
            script.AppendLine($"{indent}internal sealed class {FactoryName(scope)}");
            script.AppendLine($"{indent}{{");
            script.AppendLine($"{indent}    private readonly {ChoicesName(scope)} _choices;");
            script.AppendLine($"{indent}    private readonly global::reromanlee.Mocker.Dependencies _dependencies;");
            script.AppendLine($"{indent}    private readonly global::System.Collections.Generic.List<string> _resolving = new global::System.Collections.Generic.List<string>();");
            script.AppendLine($"{indent}    private readonly global::System.Collections.Generic.List<object> _created = new global::System.Collections.Generic.List<object>();");
            script.AppendLine();

            foreach (MockerTarget branch in scope.Branches)
            {
                if (branch.Role == MockerRole.Node)
                {
                    script.AppendLine($"{indent}    private {ScriptNames.Qualified(branch.Type.FullName)} _{scope.GetId(branch)};");
                }
            }

            foreach (MockerTarget component in scope.Components)
            {
                script.AppendLine($"{indent}    private {ScriptNames.Qualified(component.Type.FullName)} _{scope.GetId(component)};");
                script.AppendLine($"{indent}    private {Task} _init{scope.GetId(component)};");
            }

            script.AppendLine();
            script.AppendLine($"{indent}    public {FactoryName(scope)}({ChoicesName(scope)} choices, global::reromanlee.Mocker.Dependencies dependencies)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        _choices = choices ?? new {ChoicesName(scope)}();");
            script.AppendLine($"{indent}        _dependencies = dependencies ?? new global::reromanlee.Mocker.Dependencies();");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    public global::System.Collections.Generic.List<object> Created");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        get {{ return _created; }}");
            script.AppendLine($"{indent}    }}");

            foreach (MockerTarget branch in scope.Branches)
            {
                if (branch.Role == MockerRole.Node)
                {
                    AppendNodeFactory(script, indent, scope, branch);
                }
            }

            foreach (MockerTarget component in scope.Components)
            {
                AppendComponentFactory(context, script, indent, scope, component, all);
                AppendComponentInitializer(script, indent, scope, component);
            }

            AppendResolveGuards(script, indent);
            script.AppendLine($"{indent}}}");
        }

        private static void AppendNodeFactory(StringBuilder script, string indent, MockerScope scope, MockerTarget node)
        {
            string id = scope.GetId(node);
            List<string> arguments = new List<string>();

            foreach (MockerTarget child in scope.Tree.GetChildren(node))
            {
                arguments.Add($"Create{scope.GetId(child)}()");
            }

            script.AppendLine();
            script.AppendLine($"{indent}    public {ScriptNames.Qualified(node.Type.FullName)} Create{id}()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        if (_{id} != null)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            return _{id};");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        _{id} = new {ScriptNames.Qualified(node.Type.FullName)}({string.Join(", ", arguments)});");
            script.AppendLine($"{indent}        _created.Add(_{id});");
            script.AppendLine();
            script.AppendLine($"{indent}        return _{id};");
            script.AppendLine($"{indent}    }}");
        }

        private static void AppendComponentFactory(SourceProductionContext context, StringBuilder script, string indent, MockerScope scope, MockerTarget component, ImmutableArray<MockerTarget> all)
        {
            string id = scope.GetId(component);
            string type = ScriptNames.Qualified(component.Type.FullName);

            script.AppendLine();
            script.AppendLine($"{indent}    public {type} Create{id}()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        if (_{id} != null)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            return _{id};");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        BeginResolve(\"{scope.GetPath(component)}\");");
            script.AppendLine();
            script.AppendLine($"{indent}        switch ({scope.GetChoicesAccessor(component)})");
            script.AppendLine($"{indent}        {{");

            foreach (MockerTarget implementor in scope.GetImplementors(component))
            {
                string arguments = BuildArguments(context, scope, component, implementor, all);

                script.AppendLine($"{indent}            case {scope.GetEnumType(component)}.{implementor.Name}:");
                script.AppendLine($"{indent}                _{id} = new {ScriptNames.Qualified(implementor.Type.FullName)}({arguments});");
                script.AppendLine($"{indent}                break;");
            }

            script.AppendLine($"{indent}            default:");
            script.AppendLine($"{indent}                _{id} = new {scope.GetMockType(component)}();");
            script.AppendLine($"{indent}                break;");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        EndResolve();");
            script.AppendLine($"{indent}        _created.Add(_{id});");
            script.AppendLine();
            script.AppendLine($"{indent}        return _{id};");
            script.AppendLine($"{indent}    }}");
        }

        private static string BuildArguments(SourceProductionContext context, MockerScope scope, MockerTarget component, MockerTarget implementor, ImmutableArray<MockerTarget> all)
        {
            List<string> arguments = new List<string>();

            foreach (string parameterType in implementor.Details.ParameterTypes)
            {
                MockerTarget dependency;

                if (scope.TryGetComponent(parameterType, out dependency))
                {
                    arguments.Add($"Create{scope.GetId(dependency)}()");

                    continue;
                }

                ReportForeignComponent(context, scope, implementor, parameterType, all);

                arguments.Add($"_dependencies.Require<{parameterType}>(\"{scope.GetPath(component)}\", \"{implementor.Type.Name}\")");
            }

            return string.Join(", ", arguments);
        }

        private static void ReportForeignComponent(SourceProductionContext context, MockerScope scope, MockerTarget implementor, string parameterType, ImmutableArray<MockerTarget> all)
        {
            foreach (MockerTarget candidate in all)
            {
                if (candidate.Role != MockerRole.Component)
                {
                    continue;
                }

                if (!string.Equals(ScriptNames.Qualified(candidate.Type.FullName), parameterType, StringComparison.Ordinal))
                {
                    continue;
                }

                string owner;
                string path;

                if (scope.Tree.Resolve(candidate, out path, out owner) == MockerStatus.Resolved)
                {
                    context.Report(MockerDiagnostics.ForeignComponent, implementor.Location, implementor.Type.Name, candidate.Type.Name, owner);
                }

                return;
            }
        }

        private static void AppendComponentInitializer(StringBuilder script, string indent, MockerScope scope, MockerTarget component)
        {
            string id = scope.GetId(component);

            script.AppendLine();
            script.AppendLine($"{indent}    public {Task} Initialize{id}Async({Token} cancellationToken)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        if (_init{id} == null)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            _init{id} = Run{id}Async(cancellationToken);");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        return _init{id};");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    private async {Task} Run{id}Async({Token} cancellationToken)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        switch ({scope.GetChoicesAccessor(component)})");
            script.AppendLine($"{indent}        {{");

            foreach (MockerTarget implementor in scope.GetImplementors(component))
            {
                script.AppendLine($"{indent}            case {scope.GetEnumType(component)}.{implementor.Name}:");

                foreach (string parameterType in implementor.Details.ParameterTypes)
                {
                    MockerTarget dependency;

                    if (scope.TryGetComponent(parameterType, out dependency))
                    {
                        script.AppendLine($"{indent}                await Initialize{scope.GetId(dependency)}Async(cancellationToken);");
                    }
                }

                if (implementor.Details.IsAsyncInitializable)
                {
                    script.AppendLine($"{indent}                await (({ScriptNames.Qualified(implementor.Type.FullName)})_{id}).InitializeAsync(cancellationToken);");
                }

                script.AppendLine($"{indent}                break;");
            }

            script.AppendLine($"{indent}            default:");
            script.AppendLine($"{indent}                break;");
            script.AppendLine($"{indent}        }}");
            script.AppendLine($"{indent}    }}");
        }

        private static void AppendResolveGuards(StringBuilder script, string indent)
        {
            script.AppendLine();
            script.AppendLine($"{indent}    private void BeginResolve(string path)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        if (_resolving.Contains(path))");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            _resolving.Add(path);");
            script.AppendLine($"{indent}            throw new global::System.InvalidOperationException(\"Cycle: \" + string.Join(\" -> \", _resolving.ToArray()) + \". One of these has to stop taking the other in its constructor.\");");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        _resolving.Add(path);");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    private void EndResolve()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        _resolving.RemoveAt(_resolving.Count - 1);");
            script.AppendLine($"{indent}    }}");
        }

        private static void AppendComposite(StringBuilder script, string indent, MockerScope scope)
        {
            string composite = scope.Composite.Type.Name;
            string factory = FactoryName(scope);
            string choices = ChoicesName(scope);
            List<string> baseArguments = new List<string>();

            foreach (MockerTarget child in scope.Tree.GetChildren(scope.Composite))
            {
                baseArguments.Add($"factory.Create{scope.GetId(child)}()");
            }

            script.AppendLine($"{indent}/// <summary>{composite} with the implementors this assembly can see. This is the one to construct.</summary>");
            script.AppendLine($"{indent}public class {composite}Composite : {ScriptNames.Qualified(scope.Composite.Type.FullName)}");
            script.AppendLine($"{indent}{{");
            script.AppendLine($"{indent}    private readonly {factory} _factory;");
            script.AppendLine($"{indent}    private readonly {choices} _choices;");
            script.AppendLine($"{indent}    private readonly global::System.Threading.CancellationTokenSource _cancellation = new global::System.Threading.CancellationTokenSource();");
            script.AppendLine($"{indent}    private int _state;");
            script.AppendLine();
            script.AppendLine($"{indent}    public {composite}Composite({choices} choices, global::reromanlee.Mocker.Dependencies dependencies)");
            script.AppendLine($"{indent}        : this(new {factory}(choices, dependencies), choices)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    private {composite}Composite({factory} factory, {choices} choices)");
            script.AppendLine($"{indent}        : base({string.Join(", ", baseArguments)})");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        _factory = factory;");
            script.AppendLine($"{indent}        _choices = choices ?? new {choices}();");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>The choices this was built from, so code can branch on what it actually got.</summary>");
            script.AppendLine($"{indent}    public {choices} Choices");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        get {{ return _choices; }}");
            script.AppendLine($"{indent}    }}");

            AppendInitialize(script, indent, scope, composite);
            AppendDispose(script, indent, composite);

            script.AppendLine($"{indent}}}");
        }

        private static void AppendInitialize(StringBuilder script, string indent, MockerScope scope, string composite)
        {
            script.AppendLine();
            script.AppendLine($"{indent}    public override async {Task} InitializeAsync({Token} cancellationToken)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        if (_state == 3)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            throw new global::System.ObjectDisposedException(\"{composite}\");");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        if (_state != 0)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            throw new global::System.InvalidOperationException(\"{composite} was already initialized.\");");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        _state = 1;");
            script.AppendLine();
            script.AppendLine($"{indent}        using (global::System.Threading.CancellationTokenSource linked = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _cancellation.Token))");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            await OnBeforeInitialize(linked.Token);");
            script.AppendLine();

            List<string> started = new List<string>();

            foreach (MockerTarget component in scope.Components)
            {
                string local = "start" + scope.GetId(component);

                started.Add(local);
                script.AppendLine($"{indent}            {Task} {local} = _factory.Initialize{scope.GetId(component)}Async(linked.Token);");
            }

            if (started.Count > 0)
            {
                script.AppendLine();
            }

            foreach (string local in started)
            {
                script.AppendLine($"{indent}            await {local};");
            }

            if (started.Count > 0)
            {
                script.AppendLine();
            }

            script.AppendLine($"{indent}            await OnInitialized(linked.Token);");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        _state = 2;");
            script.AppendLine($"{indent}    }}");
        }

        private static void AppendDispose(StringBuilder script, string indent, string composite)
        {
            script.AppendLine();
            script.AppendLine($"{indent}    public override void Dispose()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        if (_state == 3)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            return;");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        _state = 3;");
            script.AppendLine($"{indent}        IsDisposed = true;");
            script.AppendLine($"{indent}        _cancellation.Cancel();");
            script.AppendLine($"{indent}        OnBeforeDispose();");
            script.AppendLine();
            script.AppendLine($"{indent}        global::System.Collections.Generic.List<global::System.Exception> failures = null;");
            script.AppendLine($"{indent}        global::System.Collections.Generic.List<object> created = _factory.Created;");
            script.AppendLine();
            script.AppendLine($"{indent}        for (int index = created.Count - 1; index >= 0; index--)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            global::System.IDisposable disposable = created[index] as global::System.IDisposable;");
            script.AppendLine();
            script.AppendLine($"{indent}            if (disposable == null)");
            script.AppendLine($"{indent}            {{");
            script.AppendLine($"{indent}                continue;");
            script.AppendLine($"{indent}            }}");
            script.AppendLine();
            script.AppendLine($"{indent}            try");
            script.AppendLine($"{indent}            {{");
            script.AppendLine($"{indent}                disposable.Dispose();");
            script.AppendLine($"{indent}            }}");
            script.AppendLine($"{indent}            catch (global::System.Exception exception)");
            script.AppendLine($"{indent}            {{");
            script.AppendLine($"{indent}                if (failures == null)");
            script.AppendLine($"{indent}                {{");
            script.AppendLine($"{indent}                    failures = new global::System.Collections.Generic.List<global::System.Exception>();");
            script.AppendLine($"{indent}                }}");
            script.AppendLine();
            script.AppendLine($"{indent}                failures.Add(exception);");
            script.AppendLine($"{indent}            }}");
            script.AppendLine($"{indent}        }}");
            script.AppendLine();
            script.AppendLine($"{indent}        _cancellation.Dispose();");
            script.AppendLine($"{indent}        OnDisposed();");
            script.AppendLine();
            script.AppendLine($"{indent}        if (failures != null)");
            script.AppendLine($"{indent}        {{");
            script.AppendLine($"{indent}            throw new global::System.AggregateException(\"{composite} did not dispose cleanly.\", failures);");
            script.AppendLine($"{indent}        }}");
            script.AppendLine($"{indent}    }}");
        }
    }
}
