using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the API itself: the property on a composite or node for every child that hangs off it, and
    /// the constructor that fills them. This is generated where the types are declared, because a partial
    /// class can only be completed inside its own assembly.
    /// </summary>
    internal static class MockerApiWriter
    {
        /// <summary>
        /// Writes a part for every composite and node declared in this assembly.
        /// </summary>
        /// <param name="context">Context the scripts are added to.</param>
        /// <param name="local">Everything declared in this assembly.</param>
        /// <param name="tree">Resolved parent links, used to find each type's children.</param>
        public static void Write(SourceProductionContext context, ImmutableArray<MockerTarget> local, MockerTree tree)
        {
            foreach (MockerTarget target in local)
            {
                bool isBranch = target.Role == MockerRole.Composite || target.Role == MockerRole.Node;

                if (!isBranch || !target.IsPartial)
                {
                    continue;
                }

                context.AddScript(target.Type.FullName + ".Api", BuildScript(target, tree.GetChildren(target)));
            }
        }

        private static string BuildScript(MockerTarget target, List<MockerTarget> children)
        {
            StringBuilder script = new StringBuilder();
            string indent = target.Type.HasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (target.Type.HasNamespace)
            {
                script.AppendLine($"namespace {target.Type.Namespace}");
                script.AppendLine("{");
            }

            bool isComposite = target.Role == MockerRole.Composite;
            string bases = isComposite ? " : global::System.IDisposable" : string.Empty;

            script.AppendLine($"{indent}partial class {target.Type.Name}{bases}");
            script.AppendLine($"{indent}{{");

            AppendFields(script, indent, children);
            AppendConstructor(script, indent, target, children);
            AppendProperties(script, indent, children, isComposite, target.Type.Name);

            if (isComposite)
            {
                AppendLifecycle(script, indent);
            }

            script.AppendLine($"{indent}}}");

            if (target.Type.HasNamespace)
            {
                script.AppendLine("}");
            }

            return script.ToString();
        }

        private static void AppendFields(StringBuilder script, string indent, List<MockerTarget> children)
        {
            foreach (MockerTarget child in children)
            {
                script.AppendLine($"{indent}    private readonly {ScriptNames.Qualified(child.Type.FullName)} {ScriptNames.ToField(child.Name)};");
            }

            if (children.Count > 0)
            {
                script.AppendLine();
            }
        }

        private static void AppendConstructor(StringBuilder script, string indent, MockerTarget target, List<MockerTarget> children)
        {
            List<string> parameters = new List<string>();

            foreach (MockerTarget child in children)
            {
                parameters.Add($"{ScriptNames.Qualified(child.Type.FullName)} {ScriptNames.ToParameter(child.Name)}");
            }

            string accessibility = target.Role == MockerRole.Composite ? "protected" : "public";

            script.AppendLine($"{indent}    {accessibility} {target.Type.Name}({string.Join(", ", parameters)})");
            script.AppendLine($"{indent}    {{");

            foreach (MockerTarget child in children)
            {
                script.AppendLine($"{indent}        {ScriptNames.ToField(child.Name)} = {ScriptNames.ToParameter(child.Name)};");
            }

            script.AppendLine($"{indent}    }}");
        }

        private static void AppendLifecycle(StringBuilder script, string indent)
        {
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Set by the generated subclass once this has been disposed.</summary>");
            script.AppendLine($"{indent}    protected bool IsDisposed;");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Starts every component that needs it, overlapping the ones that do not depend on each other.</summary>");
            script.AppendLine($"{indent}    public abstract global::System.Threading.Tasks.Task InitializeAsync(global::System.Threading.CancellationToken cancellationToken);");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Tears everything down in reverse of the order it was built.</summary>");
            script.AppendLine($"{indent}    public abstract void Dispose();");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Runs before anything is initialized. Fields of a derived class are set by now.</summary>");
            script.AppendLine($"{indent}    protected virtual global::System.Threading.Tasks.Task OnBeforeInitialize(global::System.Threading.CancellationToken cancellationToken)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        return global::System.Threading.Tasks.Task.CompletedTask;");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Runs once everything has finished initializing.</summary>");
            script.AppendLine($"{indent}    protected virtual global::System.Threading.Tasks.Task OnInitialized(global::System.Threading.CancellationToken cancellationToken)");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}        return global::System.Threading.Tasks.Task.CompletedTask;");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Runs before anything is disposed.</summary>");
            script.AppendLine($"{indent}    protected virtual void OnBeforeDispose()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}    }}");
            script.AppendLine();
            script.AppendLine($"{indent}    /// <summary>Runs once everything has been disposed.</summary>");
            script.AppendLine($"{indent}    protected virtual void OnDisposed()");
            script.AppendLine($"{indent}    {{");
            script.AppendLine($"{indent}    }}");
        }

        private static void AppendProperties(StringBuilder script, string indent, List<MockerTarget> children, bool guardDisposed, string compositeName)
        {
            foreach (MockerTarget child in children)
            {
                script.AppendLine();
                script.AppendLine($"{indent}    public {ScriptNames.Qualified(child.Type.FullName)} {ScriptNames.Escape(child.Name)}");
                script.AppendLine($"{indent}    {{");
                script.AppendLine($"{indent}        get");
                script.AppendLine($"{indent}        {{");

                if (guardDisposed)
                {
                    script.AppendLine($"{indent}            if (IsDisposed)");
                    script.AppendLine($"{indent}            {{");
                    script.AppendLine($"{indent}                throw new global::System.ObjectDisposedException(\"{compositeName}\");");
                    script.AppendLine($"{indent}            }}");
                    script.AppendLine();
                }

                script.AppendLine($"{indent}            return {ScriptNames.ToField(child.Name)};");
                script.AppendLine($"{indent}        }}");
                script.AppendLine($"{indent}    }}");
            }
        }
    }
}
