using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes one enum per component listing every implementor of it. This only runs in the assembly
    /// marked as the composition root, because that is the only assembly that sees both sides: an
    /// implementor must reference the assembly declaring its component, so that assembly can never
    /// reference the implementors back, and only a third assembly downstream of both sees everything.
    /// </summary>
    internal static class MockerEnumWriter
    {
        private const string NameSuffix = "Implementor";

        /// <summary>
        /// Member every enum starts with, so that the default value means nothing was selected rather
        /// than whichever implementor happens to sort first.
        /// </summary>
        public const string NoneMember = "None";

        /// <summary>
        /// Writes an enum for every component that belongs to a composite.
        /// </summary>
        /// <param name="context">Context the scripts are added to.</param>
        /// <param name="all">Everything known, declared here and published by referenced assemblies.</param>
        /// <param name="tree">Resolved parent links.</param>
        public static void Write(SourceProductionContext context, ImmutableArray<MockerTarget> all, MockerTree tree)
        {
            foreach (MockerTarget component in all)
            {
                string path;
                string rootFullName;

                if (component.Role != MockerRole.Component || tree.Resolve(component, out path, out rootFullName) != MockerStatus.Resolved)
                {
                    continue;
                }

                context.AddScript(component.Type.FullName + "." + NameSuffix, BuildScript(component, GetImplementorNames(component, all)));
            }
        }

        private static List<string> GetImplementorNames(MockerTarget component, ImmutableArray<MockerTarget> all)
        {
            List<string> names = new List<string>();

            foreach (MockerTarget target in all)
            {
                if (target.Role == MockerRole.Implementor && string.Equals(target.ParentFullName, component.Type.FullName, StringComparison.Ordinal))
                {
                    names.Add(target.Name);
                }
            }

            names.Sort(StringComparer.Ordinal);

            return names;
        }

        private static string BuildScript(MockerTarget component, List<string> implementorNames)
        {
            StringBuilder script = new StringBuilder();
            string indent = component.Type.HasNamespace ? "    " : string.Empty;

            script.AppendLine("// <auto-generated />");

            if (component.Type.HasNamespace)
            {
                script.AppendLine($"namespace {component.Type.Namespace}");
                script.AppendLine("{");
            }

            script.AppendLine($"{indent}public enum {TrimInterfacePrefix(component.Type.Name)}{NameSuffix}");
            script.AppendLine($"{indent}{{");
            script.AppendLine($"{indent}    {NoneMember} = 0{(implementorNames.Count == 0 ? string.Empty : ",")}");

            for (int index = 0; index < implementorNames.Count; index++)
            {
                bool isLast = index == implementorNames.Count - 1;

                script.AppendLine($"{indent}    {implementorNames[index]}{(isLast ? string.Empty : ",")}");
            }

            script.AppendLine($"{indent}}}");

            if (component.Type.HasNamespace)
            {
                script.AppendLine("}");
            }

            return script.ToString();
        }

        private static string TrimInterfacePrefix(string typeName)
        {
            bool looksLikeInterface = typeName.Length > 1 && typeName[0] == 'I' && char.IsUpper(typeName[1]);

            return looksLikeInterface ? typeName.Substring(1) : typeName;
        }
    }
}
