using GeneratorLibrary.Common;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace GeneratorLibrary.Mocker
{
    /// <summary>
    /// Writes the configuration a composite is constructed with: one class per branch, mirroring the API,
    /// so that choices.Ads.Interstitial sits where Ads.Interstitial does. Plain classes holding enums, so
    /// nothing here depends on the project or on Unity.
    /// </summary>
    internal static class MockerChoicesWriter
    {
        /// <summary>
        /// Writes the whole choices tree for one composite.
        /// </summary>
        /// <param name="context">Context the script is added to.</param>
        /// <param name="scope">The composite and everything under it.</param>
        public static void Write(SourceProductionContext context, MockerScope scope)
        {
            ScriptEmitter emitter = new ScriptEmitter();

            emitter.Line("// <auto-generated />");

            using (emitter.Namespace(scope.Composite.Type.Namespace))
            {
                for (int index = 0; index < scope.Branches.Count; index++)
                {
                    if (index > 0)
                    {
                        emitter.Line();
                    }

                    WriteBranch(emitter, scope, scope.Branches[index]);
                }
            }

            context.AddScript(scope.Composite.Type.FullName + ".Choices", emitter.ToString());
        }

        private static void WriteBranch(ScriptEmitter emitter, MockerScope scope, MockerTarget branch)
        {
            List<MockerTarget> children = scope.Tree.GetChildren(branch);

            emitter.Line($"/// <summary>Which implementor to use for everything under {scope.GetPath(branch)}.</summary>");

            using (emitter.Block($"public sealed class {scope.GetChoicesTypeName(branch)}"))
            {
                foreach (MockerTarget child in children)
                {
                    if (child.Role == MockerRole.Node)
                    {
                        string childType = QualifiedChoices(scope, child);

                        emitter.Line($"public {childType} {ScriptNames.Escape(child.Name)} {{ get; }} = new {childType}();");
                    }
                    else if (child.Role == MockerRole.Component)
                    {
                        emitter.Line($"public {scope.GetEnumType(child)} {ScriptNames.Escape(child.Name)} {{ get; set; }}");
                    }
                }
            }
        }

        private static string QualifiedChoices(MockerScope scope, MockerTarget branch)
        {
            string name = scope.GetChoicesTypeName(branch);

            return scope.Composite.Type.HasNamespace
                ? ScriptNames.Qualified(scope.Composite.Type.Namespace + "." + name)
                : ScriptNames.Qualified(name);
        }
    }
}
