using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace GeneratorLibrary
{
    [Generator]
    public class SimpleClassInjection : IIncrementalGenerator
    {
        private const string ScriptName = "SimpleClassInjection";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValueProvider<bool> isTargetAssembly = context.ObserveTargetAssembly();

            IncrementalValueProvider<ImmutableArray<string>> classNames = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => ((ClassDeclarationSyntax)ctx.Node).Identifier.Text
            ).Collect();

            context.RegisterSourceOutput(isTargetAssembly.Combine(classNames), (productionContext, source) =>
            {
                if (!source.Left)
                {
                    return;
                }

                productionContext.AddScript(ScriptName, BuildScript(source.Right));
            });
        }

        private static string BuildScript(ImmutableArray<string> classNames)
        {
            StringBuilder extensions = new StringBuilder();

            foreach (string className in classNames.Distinct().OrderBy(name => name, StringComparer.Ordinal))
            {
                extensions.AppendLine($@"    public static class {className}Extensions
    {{
        public static void LogGenerated(this {className} obj)
        {{
            UnityEngine.Debug.Log(""Hello from incremental generator for {className}!"");
        }}
    }}");
            }

            return $@"// <auto-generated />
namespace MyGame.Generated
{{
{extensions}}}";
        }
    }
}
